require('plug')
require('settings')
require('mapping')
--require('plugins/nvim-tree')
require('plugins/lualine')
require('plugins/zig')
--require('plugins/fzf')
require('plugins/treesitter')
require('plugins/coq')
require('plugins/lspconfig')
require('plugins/nvim-web-devicons-config')
require('plugins/vimwiki')
require('plugins/telescopeconfig')

require('telescope').setup{  defaults = { file_ignore_patterns = { "plugged", ".git", "__pycache__" }} }
