require('plug')
require('settings')
require('mapping')
require('plugins/nvim-tree')
-- TO FIX
-- require('plugins/vista')
require('plugins/lualine')
require('plugins/zig')
require('plugins/fzf')
require('plugins/treesitter')
require('plugins/coq')
require('plugins/lspconfig')
